name: Check Grimey Blog

on:
  schedule:
    - cron: '0 12 * * *'  # Ejecuta el script todos los días a las 12:00 PM UTC

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install requests-html

    - name: Run script
      run: python check_grimey.py
